name: "Lint and Test"

on:
  push:
    branches:
      - '**'
    tags:
      - '!**'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 1
    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip -q install -r requirements.txt
        pip -q install -r requirements-dev.txt
    - name: Analysing the code with black
      run: |
        black --check setup.py odmpy
    - name: Analysing the code with flake8
      run: |
        flake8 setup.py odmpy
    - name: Analysing the code with pylint
      run: |
        pylint setup.py odmpy

  tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: FedericoCarboni/setup-ffmpeg@v2
      id: setup-ffmpeg
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 1
    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip -q install -r requirements.txt
    - name: Run tests
      run: sh run_tests.sh
