name: "Lint and Test"

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip -q install -r requirements.txt
        pip -q install pylint flake8 black
    - name: Analysing the code with black
      run: |
        black --check setup.py odmpy
    - name: Analysing the code with flake8
      run: |
        flake8 setup.py odmpy
    - name: Analysing the code with pylint
      run: |
        pylint setup.py odmpy

  tests:
    runs-on: ubuntu-latest
    needs: lint

    steps:
    - uses: FedericoCarboni/setup-ffmpeg@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      id: setup-ffmpeg
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip -q install -r requirements.txt
    - name: Run tests
      run: sh run_tests.sh
